# Acknowledgement

https://github.com/zekelabs/data-science-complete-tutorial



# 1. Introduction to Numpy
Numpy is a Library in python that specializes in dealing with multidimensional Arrays. The cool features of Numpy are
* **Automatic Checking :** Numpy ndArrays automatically check the consistancy of data. For instance, it is not possible to have 1st row with 2 elements and 2nd row with 3 elements
* **Contiguous Storage :** Unlike Python Lists, Numpy stores the data in contiguous Memory Locations, leading to lesser Space
* **Faster Vector Arithmatics :** Because of contiguous storage, the operations are performed faster as compared to default Python Execution for Lists

In [1]:
# Importing Numpy
import numpy as np

## 1.1 Initialization of 1D array in Python
A numpy array comes with 2 important state variables. Just like Python, it automatically detects dtype (if not mentioned)
* dtype
* shape

#### 1.1.1 Initialization from python List
numpy.array( list **)**


In [2]:
# Initializing from Python List
v = np.array([1,4,9,3,2, 2020.617])
print ('1D array in numpy is %s\n'%v)
print ('dtype of the numpy array is %s\n'%str(v.dtype))
print ('shape of the numpy array is %s\n'%v.shape)

1D array in numpy is [1.000000e+00 4.000000e+00 9.000000e+00 3.000000e+00 2.000000e+00
 2.020617e+03]

dtype of the numpy array is float64

shape of the numpy array is 6



#### 1.1.2 Initialization via arange
numpy.arange(**\[**start, **\]**stop, **\[**step, **\]** dtype=None)

In [3]:
v1 = np.arange(3)
print ('Creating a numpy array via arange (stop=5) : %s\n'%v1)
v2 = np.arange(2,4)
print ('Creating a numpy array via arange (start=2,stop=5) : %s\n'%v2)
v3 = np.arange(0,-8,-2)
print ('Creating a numpy array via arange (start=0,stop=-10,step=-2) : %s\n'%v3)



Creating a numpy array via arange (stop=5) : [0 1 2]

Creating a numpy array via arange (start=2,stop=5) : [2 3]

Creating a numpy array via arange (start=0,stop=-10,step=-2) : [ 0 -2 -4 -6]



## 1.2. Initialization of 2D array in Python
When we talk about 2D array, it is important to note that Numpy stores Matrix is ***Row Major Format***. Row major format means that the the complete row will be stored first and then the next row will be stored and so on. You can choose to store a matrix in colum major format by mentioning ***order='F'*** on ndarray creation, which means ***Column Major Format***  or *Fortran Style Format*. 


#### 1.2.1 Initialization from List of List
numpy.array **(** ***object***, dtype=None **)**

Here the matrix that we have taken is 
$$mat = \begin{bmatrix}1 & 2 & 3 \\ 4 & 5 & 6 \end{bmatrix}$$

#### 1.2.2 Initialization with zero/ones
numpy.**zeros**(*shape*, dtype=float)  
numpy.**ones**(*shape*, dtype=float)

In [4]:
mat_zeros = np.zeros(shape=(3,2))
print ('Zeros Matris of shape %s is \n%s\n'%(mat_zeros.shape,mat_zeros))
mat_ones = np.ones(shape=(2,3))
print ('Ones Matris of shape %s is \n%s\n'%(mat_ones.shape,mat_ones))


Zeros Matris of shape (3, 2) is 
[[0. 0.]
 [0. 0.]
 [0. 0.]]

Ones Matris of shape (2, 3) is 
[[1. 1. 1.]
 [1. 1. 1.]]



#### 1.2.3 Initialization with Random Values
**1.2.3.1** numpy.**random.random**(*size=None*,)  
**1.2.3.2** numpy.**random.randint**(low, high, *size=None*, dtype='I') : The value of matrix lies between low and high-1  
**1.2.3.3** numpy.**random.randn**($d_0,d_1,\cdots,d_n$)


In [5]:
#Using numpy.random.random
mat1 = np.random.random(size=(3,3))
print ('matrix generated from numpy.random.random is \n%s\n'%mat1)
mat2 = np.random.randint(low=0,high=2,size=(2,2))
print ('matrix generated from numpy.random.random is \n%s\n'%mat2)
mat3 = np.random.randn(2,4)
print ('matrix generated from numpy.random.randn is \n%s\n'%mat3)


matrix generated from numpy.random.random is 
[[0.06342355 0.2520227  0.16095951]
 [0.40051629 0.01783276 0.41191337]
 [0.67402647 0.38993997 0.12738349]]

matrix generated from numpy.random.random is 
[[1 0]
 [0 1]]

matrix generated from numpy.random.randn is 
[[ 0.45905139  1.6483875  -1.07853394  0.72234491]
 [-0.91919593  0.1081029   0.08308309 -0.31741253]]



## 1.3. Slicing and Indexing in Numpy
Just like python, numpy also has 0 indexing. Let us see some of the commonly used slicing techniques .  
* Generic Slicing Operation : \[start\]:\[end\]:\[jump\]
* Only jump    **::2**
* Only end    **:5**
* Start and jump **2::-1**
* End and Jump **:5:2**
* Start, end and jump **2:7:3**


#### 1.3.1 Remove n elements
vec\[:*-n*\]

In [6]:
pymat = [[1,2,3,7],[4,5,6,8]]
npmat = np.array(pymat)
print ('numpy matrix is \n%s\n'%npmat)
print ('Flattened version of numpy matrix is %s\n'%npmat.flatten())
# By flatten the matrix becomes row major 1D vector (This is the way in which a matrix is stored in memory). 


numpy matrix is 
[[1 2 3 7]
 [4 5 6 8]]

Flattened version of numpy matrix is [1 2 3 7 4 5 6 8]



In [7]:
vec = np.arange(17)
vec1 = vec[:-5]
print ('Result of removing last 3 elements from range(10) : \n%s\n'%vec1)

Result of removing last 3 elements from range(10) : 
[ 0  1  2  3  4  5  6  7  8  9 10 11]



#### 1.3.2 Access elements at even indices in a 1D array
vec[::2]

In [8]:

vec1 = np.arange(0,30,3)
print ('Original array is %s\n'%vec1)
vec2 = vec1[::2]
print ('Elements at even indices are %s\n'%vec2)


Original array is [ 0  3  6  9 12 15 18 21 24 27]

Elements at even indices are [ 0  6 12 18 24]



#### 1.3.3 Access elements at indices in reverse order
vec[::-1]

In [9]:
vec1 = np.arange(0,10,3)
print ('Original array is %s\n'%vec1)
vec2 = vec1[::-1]
print ('Elements for indices in reverse is %s\n'%vec2)

Original array is [0 3 6 9]

Elements for indices in reverse is [9 6 3 0]



#### 1.3.4 Access elements present for a range of indices
vec[a:b]

In [10]:
vec1 = np.arange(0,20,3)
print ('Original array is %s\n'%vec1)
vec2 = vec1[2:5]
print ('Elements for indices 2:5 is %s\n'%vec2)

Original array is [ 0  3  6  9 12 15 18]

Elements for indices 2:5 is [ 6  9 12]



#### 1.3.5 Access a particular set of index given by a list
vec[idxlist]

In [11]:
idx=[0,1,5]
vec1 = np.arange(0,20,3)
print ('Original array is %s\n'%vec1)
vec2 = vec1[idx]
print ('Subarray constructed by indices %s is %s\n'%(idx,vec2))

Original array is [ 0  3  6  9 12 15 18]

Subarray constructed by indices [0, 1, 5] is [ 0  3 15]



#### 1.3.6 Creating a submatrix

In [12]:
mat = np.random.randint(0,6,(3,3))
# Create a submatrix with first 2 rows and last 2 columns
submat1 = mat[0:2,-2:]
print ('Original Matrix is \n%s\n'%mat)
print ('Sub Matrix with first 2 rows and last 2 columns is \n%s\n'%submat1)
submat2 = mat[:,3:0:-1]
print ('After flipping the columns of the matrix, it looks : \n%s\n'%submat2)

Original Matrix is 
[[3 0 1]
 [4 2 5]
 [4 4 0]]

Sub Matrix with first 2 rows and last 2 columns is 
[[0 1]
 [2 5]]

After flipping the columns of the matrix, it looks : 
[[1 0]
 [5 2]
 [0 4]]



#### 1.3.7 Horizontal Matrix splitting
numpy.**hsplit**(ary, *indices_or_sections*)  
  
hsplit basically splits a matrix across the horizontal plane based on the indices. Do note that the ***number of rows*** always remains ***constant*** in each section after the horizontal splitting.

![](img/1.3.7-hsplit-01.jpg)

In [13]:
mat = np.random.randint(0,6,(3,7))
sp1,sp2,sp3 = np.hsplit(mat,[4,6])
print ('Original matrix of shape %s, is \n%s\n'%(mat.shape,mat))
print ('First split of shape %s, is \n%s\n'%(sp1.shape,sp1))
print ('Second split of shape %s, is \n%s\n'%(sp2.shape,sp2))
print ('Third split of shape %s, is \n%s\n'%(sp3.shape,sp3))

Original matrix of shape (3, 7), is 
[[5 3 1 5 3 4 1]
 [4 4 2 3 3 5 2]
 [0 5 2 2 1 0 5]]

First split of shape (3, 4), is 
[[5 3 1 5]
 [4 4 2 3]
 [0 5 2 2]]

Second split of shape (3, 2), is 
[[3 4]
 [3 5]
 [1 0]]

Third split of shape (3, 1), is 
[[1]
 [2]
 [5]]



#### 1.3.8 Vertical Matrix Splitting
numpy.**vsplit**(ary, *indices_or_sections*)  
  
vsplit is yet another operation which splits the matrix across the vertical plane based on the ***'rowwise split-index array'***. The ***number of columns*** always remain ***constant*** in each split.

In [14]:
mat = np.random.randint(0,6,(3,7))
sp1,sp2 = np.vsplit(mat,[1])
print ('Original matrix of shape %s, is \n%s\n'%(mat.shape,mat))
print ('First split of shape %s, is \n%s\n'%(sp1.shape,sp1))
print ('Second split of shape %s, is \n%s\n'%(sp2.shape,sp2))

Original matrix of shape (3, 7), is 
[[0 3 4 1 3 0 1]
 [4 1 4 1 3 2 1]
 [1 1 1 0 2 2 0]]

First split of shape (1, 7), is 
[[0 3 4 1 3 0 1]]

Second split of shape (2, 7), is 
[[4 1 4 1 3 2 1]
 [1 1 1 0 2 2 0]]



> ### *Class Examples for 1.1 to 1.3*
>
> 1. Create a matrix of size (2,3) with random binary values
> 2. Find the sum of all 2x2 blocks (overlapping) for a random integer matrix of size (3,5) 

## 1.4. Understanding - Pass By Reference 
Just like python lists, Numpy also exhibits default pass-by-reference behavior


In [15]:
mat1 = np.random.random((2,3))
pt1 = mat1[0].__array_interface__['data'][0]
print ('Memory Location of mat1[0] is : %s\n'%pt1)
pt2 = mat1[1].__array_interface__['data'][0]
print ('Memory Location of mat1[1] is : %s\n'%pt2)
print ('Difference in Memory Location for 3 elements  is : %s bytes\n'%(pt2-pt1))
print ('Memory jump = 8 bytes')


Memory Location of mat1[0] is : 4517282640

Memory Location of mat1[1] is : 4517282664

Difference in Memory Location for 3 elements  is : 24 bytes

Memory jump = 8 bytes


#### 1.4.1 Experiment : Change the value of array by Reference

In [16]:
def identity(elem):
    return elem
v = np.array([1,2,3])
v1 = v # Copy by reference
v1[0]=10
print ('Value of v, after v1 is modified is %s\n'%v)
# Pass by Function 
v = np.array([1,2,3])
v1 = identity(v) # Copy by reference
v1[0]=10
print ('Value of v after func(v) is modified is %s\n'%v)
v = np.array([1,2,3])
v1 = v.copy() # Copy by reference
v1[0]=10
print ('Value of v after v.copy() is modified is %s\n'%v)

Value of v, after v1 is modified is [10  2  3]

Value of v after func(v) is modified is [10  2  3]

Value of v after v.copy() is modified is [1 2 3]



#### 1.4.2 Experiment : Change the value of matrices by Reference

In [17]:
mat = np.array([[1,2,3],[4,5,6],[7,8,9]])
print ('Original Matrix is \n%s\n'%mat)

#1 Add 10 to all the even indexes in matrix
mat = np.array([[1,2,3],[4,5,6],[7,8,9]])
mat1 = mat[::2,::2]
mat1+=10
print (' Matrix with 10 added to even indices is \n%s\n'%mat1)
# Changes in mat1 are reflected in mat. This happens because the default assignment in numpy is 'pass by reference'

Original Matrix is 
[[1 2 3]
 [4 5 6]
 [7 8 9]]

 Matrix with 10 added to even indices is 
[[11 13]
 [17 19]]



> **Note :** mat1+=10 is different from mat1=mat1+10, as a new space is allocated for mat1 in the latter case.

## 1.5 Broadcast Operation in Numpy
Broadcast Operation is like a razor-sharp knife, to be used with great care. It is a way to ***broadcast*** data of lower or same  dimension onto another ndarray. It is similar to ***map*** operation in python, scala, hadoop.  Broadcast rules are not limited to 2D array. There are extremely specific set of rules for nd-array broadcasting. You can visit ***[numpy documentation on broadcasting](https://docs.scipy.org/doc/numpy-1.13.0/user/basics.broadcasting.html)*** to get the complete picture. However, we will be restricting the discussion to only 2D-matrices.



In [18]:
mat = np.random.randint(0,6,(3,5))
print ('mat is \n%s\n'%mat)
v = np.array([10,20,30,40,50])
print ('v is \n%s\n'%v)
print ('mat+1 is \n%s\n'%(mat+1)) # Similar behaviour in case of np.array([1])
print ('mat+v is \n%s\n'%(mat+v))
print ('mat*v is \n%s\n'%(mat*v))
print ('mat+mat is \n%s\n'%(mat+mat))
print ('mat*mat is \n%s\n'%(mat*mat))


mat is 
[[0 3 1 4 5]
 [3 4 3 2 4]
 [3 2 0 0 2]]

v is 
[10 20 30 40 50]

mat+1 is 
[[1 4 2 5 6]
 [4 5 4 3 5]
 [4 3 1 1 3]]

mat+v is 
[[10 23 31 44 55]
 [13 24 33 42 54]
 [13 22 30 40 52]]

mat*v is 
[[  0  60  30 160 250]
 [ 30  80  90  80 200]
 [ 30  40   0   0 100]]

mat+mat is 
[[ 0  6  2  8 10]
 [ 6  8  6  4  8]
 [ 6  4  0  0  4]]

mat*mat is 
[[ 0  9  1 16 25]
 [ 9 16  9  4 16]
 [ 9  4  0  0  4]]



## 1.6 Matrix Operations 
There are two major matix Operations which are important for us.
1. Inner Product
  * Vector Vector
  * Matrix Vector 
  * Matrix Matrix
2. Outer product

#### 1.6.1 Inner Product
In terms of Inner Product or Dot product, <v,w> will be be nothing but sum of element wise product.
$$<v,w> = \sum v_i*w_i = \begin{bmatrix} v_0 & v_1 & \cdots & v_n \end{bmatrix}\begin{bmatrix} w_0 \\ w_1 \\ \cdots \\ w_n \end{bmatrix}$$
So, the dot product between vector $v=[1,2,3]$ and  $w=[2,4,6]$ will be 
$$\begin{align}1*2 + 2*4 + 3*6 \\ 2+8+18 \\ 28\end{align}$$  
We will be covering matrix matrix multiplication in much depth in next-to-next chapter, but you can take it for granted as of now.
#### 1.6.2 Outer Product
The **outer product** on other end is 
$$\begin{bmatrix} v_0 \\ v_1 \\ \cdots \\ v_n \end{bmatrix}\begin{bmatrix} w_0 & w_1 & \cdots & w_n \end{bmatrix} = \begin{bmatrix}v_0w_0 & \cdots & v_0w_j & \cdots & v_0w_n \\ \vdots && \vdots && \vdots \\ v_iw_0 & \cdots & v_iw_j & \cdots & v_iw_n \\ \vdots && \vdots && \vdots \\ v_nw_0 & \cdots & v_nw_j & \cdots & v_nw_n    \end{bmatrix} $$

In [19]:
mat = np.arange(9).reshape(3,3)
vec1 = np.array([1,2,3])
vec2 = np.array([2,4,6])
print ('Vector v1 is %s\n'%vec1)
print ('Vector v2 is %s\n'%vec2)
print ('Vector Vector dot product is <v1,v2> is %s\n'%np.dot(vec1,vec2))
print ('---------------\n')

print ('Matrix is\n%s\n'%mat)
print ('Vector v2 is\n%s\n'%vec1)

print ('Matrix Vector product is <mat,vec1> is \n%s\n'%np.dot(mat,vec1))
print ('Matrix Matrix multiplication is <mat,mat> is \n%s\n'%np.dot(mat,mat))
print ('---------------\n')

print ('Vector v1 is %s\n'%vec1)
print ('Vector v2 is %s\n'%vec2)
print ('Vector Vector outer product is <v1,v2> is \n%s\n'%np.outer(vec1,vec2))


Vector v1 is [1 2 3]

Vector v2 is [2 4 6]

Vector Vector dot product is <v1,v2> is 28

---------------

Matrix is
[[0 1 2]
 [3 4 5]
 [6 7 8]]

Vector v2 is
[1 2 3]

Matrix Vector product is <mat,vec1> is 
[ 8 26 44]

Matrix Matrix multiplication is <mat,mat> is 
[[ 15  18  21]
 [ 42  54  66]
 [ 69  90 111]]

---------------

Vector v1 is [1 2 3]

Vector v2 is [2 4 6]

Vector Vector outer product is <v1,v2> is 
[[ 2  4  6]
 [ 4  8 12]
 [ 6 12 18]]



## 1.7 Statistical Functions
1. **np.mean**(data,axis=0)
2. **np.var**(data,axis=0)
3. **np.sum**(data,axis=0)
4. **np.max**(data,axis=0)
5. **np.min**(data,axis=0)
6. **np.percentile**(data, percentage,axis=0)

In [20]:

mat = np.arange(9).reshape((3,3))
print ('Original matrix is \n%s\n'%mat)
print ('Overall mean of matrix is \n%s\n'%np.mean(mat))
print ('Row mean of matrix is \n%s\n'%np.mean(mat, axis=0))
print ('Column mean of matrix is \n%s\n'%np.mean(mat, axis=1))
print ('---------------------------\n')
print ('Overall varience of matrix is %s\n'%np.var(mat))
print ('Overall sum of matrix is %s\n'%np.sum(mat))
print ('Overall min of matrix is %s\n'%np.min(mat))
print ('Overall max of matrix is %s\n'%np.max(mat))

print ('-------------------------------------\n')
marks = np.array([30,31,32,40,90,95,97,98,99,100])
print ('Marks = %s\n'%marks)
print ('Overall 30 percent quantile of marks is %s\n'%(str(np.percentile(marks,30))))


Original matrix is 
[[0 1 2]
 [3 4 5]
 [6 7 8]]

Overall mean of matrix is 
4.0

Row mean of matrix is 
[3. 4. 5.]

Column mean of matrix is 
[1. 4. 7.]

---------------------------

Overall varience of matrix is 6.666666666666667

Overall sum of matrix is 36

Overall min of matrix is 0

Overall max of matrix is 8

-------------------------------------

Marks = [ 30  31  32  40  90  95  97  98  99 100]

Overall 30 percent quantile of marks is 37.599999999999994



## 1.8 Miscellenous Functions
In this section, we will be discussing some important miscellenous Functions which come in handy for matrix manipulation.
#### 1.8.1 squeeze
numpy.**squeeze**(a,axis=None)  
This function tries to reduce the excess dimensions which have only 1 element. If we print the shape of the ndary, these excess dimension will have a 1 in that particular dimension's index. For example, a nd-matrix with shape (1,2,3,1), has $0^{th}$ and $3^{rd}$ dimension as excess.

In [21]:
ndmat = np.zeros(shape=(1,2,3,3,1))
print ('Original Shape of ndmat is %s\n'%str(ndmat.shape))
ndmat1 = np.squeeze(ndmat)
print ('Shape of np.squeeze(ndmat) is %s\n'%str(ndmat1.shape))



Original Shape of ndmat is (1, 2, 3, 3, 1)

Shape of np.squeeze(ndmat) is (2, 3, 3)



#### 1.8.2 transpose
numpy.**transpose**(a, *axes=None*)  
This function reverses the axes for 2D array.  
For multidimensional array, it permutes the matrix according to the axis argument

In [22]:
mat = np.zeros(shape=(2,3))
print ('Original Shape of 2D matrix is %s\n'%str(mat.shape))
mat_transpose = np.transpose(mat)
print ('Shape of np.transpose(mat) is %s\n'%str(mat_transpose.shape))
mat_transpose[1,0] = 1
print ('np.transpose is by yet again assignment by reference, as changes in transpose reflects in the original matrix\n')
print ('---------------------------------\n')
# NDimensional matrix
ndmat = np.zeros(shape=(2,3,4))
print ('Original Shape of nDimensional matrix is %s\n'%str(ndmat.shape))
ndmat_transpose = np.transpose(ndmat)
print ('Shape of np.transpose(ndmat) is %s\n'%str(ndmat_transpose.shape))
ndmat_special_transpose = np.transpose(ndmat, axes = [0,2,1])
print ('Shape of np.transpose(ndmat, axes=[0,2,1]) is %s\n'%str(ndmat_special_transpose.shape))


Original Shape of 2D matrix is (2, 3)

Shape of np.transpose(mat) is (3, 2)

np.transpose is by yet again assignment by reference, as changes in transpose reflects in the original matrix

---------------------------------

Original Shape of nDimensional matrix is (2, 3, 4)

Shape of np.transpose(ndmat) is (4, 3, 2)

Shape of np.transpose(ndmat, axes=[0,2,1]) is (2, 4, 3)



# Chapter 1 Assignment
1. Create a null array of size 10 but the fifth value which is 1
2. Reverse a above created array (first element becomes last)
3. Create a 3x3 matrix with values ranging from 0 to 8
4. Find indices of non-zero elements from [1,2,0,0,4,0]
5. Create a 3x3x3 array with random values
6. Create a 10x10 array with random values and find the minimum and maximum values
7. Create a random vector of size 30 and find the mean value
8. Create a 2d array with 1 on the border and 0 inside
9. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)
10. Extract the integer part of a random array
11. Create a 5x5 matrix with row values ranging from 0 to 4
12. Create a random vector of size 10 and sort it
13. Consider two random array A anb B, check if they are equal
14. How to tell if a given 2D array has null columns?
15. Considering a four dimensions array, how to get sum over the last two axis at once?
16. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)?
17. Extract all the contiguous 3x3 blocks from a random 10x10 matrix
18. Consider a 16x16 array, how to get the block-sum (block size is 4x4)?

In [27]:
# Claude Code Prompt Used to Create the Below
# Hey so at the bottom of the document there are some questions under the 
# heading Chapter 1 Assignment. If you could create a code cell below and 
# answer them that would be great! There is a formate made below for some 
# of the questions that I allready attempted if you could follow a similar 
# formate but clean it up then that would be helpful. Also, please add comments 
# and explaintions within the code for how the cells work and how the code 
# solves the problem.

# Set a global seed so every random result is reproducible
np.random.seed(42)

# ─────────────────────────────────────────────────────────────────────────────
# Question 1: Create a null (zero) array of size 10 with the fifth value = 1
# ─────────────────────────────────────────────────────────────────────────────
# np.zeros creates an array filled with 0.0 ("null" values in NumPy convention).
# The fifth element is at index 4 because Python uses 0-based indexing.
Q1 = np.zeros(10)
Q1[4] = 1
print("Question 1: Null array of size 10, fifth value = 1")
print(Q1)

# ─────────────────────────────────────────────────────────────────────────────
# Question 2: Reverse the array from Question 1
# ─────────────────────────────────────────────────────────────────────────────
# The [::-1] slice steps through the array backwards, producing a reversed view.
Q2 = Q1[::-1]
print("\nQuestion 2: Reversed array")
print(Q2)

# ─────────────────────────────────────────────────────────────────────────────
# Question 3: Create a 3×3 matrix with values ranging from 0 to 8
# ─────────────────────────────────────────────────────────────────────────────
# arange(9) produces [0, 1, ..., 8]; reshape(3,3) packs those into a 3×3 grid.
Q3 = np.arange(9).reshape(3, 3)
print("\nQuestion 3: 3×3 matrix with values 0–8")
print(Q3)

# ─────────────────────────────────────────────────────────────────────────────
# Question 4: Find indices of non-zero elements in [1, 2, 0, 0, 4, 0]
# ─────────────────────────────────────────────────────────────────────────────
# np.nonzero returns a tuple of arrays, one per axis, containing the indices
# where the array is non-zero. We take [0] to get the 1-D index array.
Q4 = np.array([1, 2, 0, 0, 4, 0])
Q4_nonzero_idx = np.nonzero(Q4)[0]
print("\nQuestion 4: Indices of non-zero elements in", Q4)
print(Q4_nonzero_idx)

# ─────────────────────────────────────────────────────────────────────────────
# Question 5: Create a 3×3×3 array with random values
# ─────────────────────────────────────────────────────────────────────────────
# np.random.random fills an array of any shape with uniform values in [0, 1).
Q5 = np.random.random((3, 3, 3))
print("\nQuestion 5: 3×3×3 random array")
print(Q5)

# ─────────────────────────────────────────────────────────────────────────────
# Question 6: Create a 10×10 random array and find its minimum and maximum
# ─────────────────────────────────────────────────────────────────────────────
Q6 = np.random.random((10, 10))
print("\nQuestion 6: Min and Max of a 10×10 random array")
print(f"  Max: {Q6.max():.6f}")
print(f"  Min: {Q6.min():.6f}")

# ─────────────────────────────────────────────────────────────────────────────
# Question 7: Create a random vector of size 30 and find its mean
# ─────────────────────────────────────────────────────────────────────────────
Q7 = np.random.random(30)          # 1-D vector of 30 uniform random values
print("\nQuestion 7: Mean of a size-30 random vector")
print(Q7)
print(f"  Mean: {Q7.mean():.6f}")

# ─────────────────────────────────────────────────────────────────────────────
# Question 8: Create a 2-D array with 1 on the border and 0 inside
# ─────────────────────────────────────────────────────────────────────────────
# Start with all ones, then zero out every interior element in one slice.
# [1:-1, 1:-1] selects all rows and columns that are NOT on the border.
Q8 = np.ones((5, 5))
Q8[1:-1, 1:-1] = 0
print("\nQuestion 8: 5×5 array with 1-border and 0-interior")
print(Q8)

# ─────────────────────────────────────────────────────────────────────────────
# Question 9: Multiply a 5×3 matrix by a 3×2 matrix (real matrix product)
# ─────────────────────────────────────────────────────────────────────────────
# np.dot (or the @ operator) computes standard matrix multiplication.
# The inner dimensions must match: (5,3) @ (3,2) → result is (5,2).
Q9_A = np.random.randint(0, 10, (5, 3))   # 5×3 matrix
Q9_B = np.random.randint(0, 10, (3, 2))   # 3×2 matrix
Q9 = np.dot(Q9_A, Q9_B)                   # equivalent to Q9_A @ Q9_B
print("\nQuestion 9: 5×3 @ 3×2 matrix product (result shape is 5×2)")
print(Q9)

# ─────────────────────────────────────────────────────────────────────────────
# Question 10: Extract the integer part of a random array
# ─────────────────────────────────────────────────────────────────────────────
# np.random.uniform draws values from [0, 10) so the integer parts are visible.
# np.floor rounds each element down to the nearest integer (truncates decimals).
Q10 = np.random.uniform(0, 10, (5, 5))
Q10_int = np.floor(Q10).astype(int)
print("\nQuestion 10: Integer part of a random array (values in [0, 10))")
print("  Original (2 decimals):")
print(np.round(Q10, 2))
print("  Integer part:")
print(Q10_int)

# ─────────────────────────────────────────────────────────────────────────────
# Question 11: Create a 5×5 matrix where each row contains values 0 to 4
# ─────────────────────────────────────────────────────────────────────────────
# np.tile(v, (5,1)) stacks the row vector v five times, giving each row [0,1,2,3,4].
Q11 = np.tile(np.arange(5), (5, 1))
print("\nQuestion 11: 5×5 matrix with each row = [0, 1, 2, 3, 4]")
print(Q11)

# ─────────────────────────────────────────────────────────────────────────────
# Question 12: Create a random vector of size 10 and sort it
# ─────────────────────────────────────────────────────────────────────────────
# np.sort returns a sorted copy without modifying the original array.
Q12 = np.random.random(10)
Q12_sorted = np.sort(Q12)
print("\nQuestion 12: Sorted random vector of size 10")
print(f"  Original: {np.round(Q12, 4)}")
print(f"  Sorted:   {np.round(Q12_sorted, 4)}")

# ─────────────────────────────────────────────────────────────────────────────
# Question 13: Check if two random arrays A and B are equal
# ─────────────────────────────────────────────────────────────────────────────
# np.array_equal returns True only if both arrays have the same shape AND every
# corresponding element is identical.  Two independently drawn random arrays
# will almost certainly NOT be equal.
Q13_A = np.random.random((2, 3))
Q13_B = np.random.random((2, 3))
print("\nQuestion 13: Are two independent random (2,3) arrays equal?")
print(f"  Equal: {np.array_equal(Q13_A, Q13_B)}")

# ─────────────────────────────────────────────────────────────────────────────
# Question 14: How to tell if a given 2-D array has null (NaN) columns?
# ─────────────────────────────────────────────────────────────────────────────
# np.isnan marks each element True if it is NaN.
# np.all(..., axis=0) checks whether EVERY row in each column is NaN.
# A True result for a column means that entire column is null.
Q14 = np.random.random((5, 4))
Q14[:, 1] = np.nan                         # artificially make column 1 all-NaN
Q14_null_cols = np.all(np.isnan(Q14), axis=0)
print("\nQuestion 14: Which columns of a (5,4) array are entirely NaN?")
print(f"  Null-column mask (True = null): {Q14_null_cols}")
print(f"  Null column indices:            {np.where(Q14_null_cols)[0]}")

# ─────────────────────────────────────────────────────────────────────────────
# Question 15: Sum over the last two axes of a 4-D array at once
# ─────────────────────────────────────────────────────────────────────────────
# Passing axis as a tuple tells NumPy to reduce multiple axes in one call.
# axis=(-2, -1) refers to the third and fourth dimensions regardless of total rank.
Q15 = np.random.random((2, 3, 4, 5))
Q15_sum = Q15.sum(axis=(-2, -1))
print("\nQuestion 15: Sum over last two axes of a (2,3,4,5) array")
print(f"  Input shape:  {Q15.shape}")
print(f"  Output shape: {Q15_sum.shape}   (axes 2 and 3 were collapsed)")
print(Q15_sum)

# ─────────────────────────────────────────────────────────────────────────────
# Question 16: Multiply a (5,5,3) array by a (5,5) array
# ─────────────────────────────────────────────────────────────────────────────
# NumPy broadcasting requires trailing dimensions to match.
# B has shape (5,5); A has shape (5,5,3).  We expand B to (5,5,1) with
# np.newaxis so NumPy can broadcast the multiplication along A's last axis.
Q16_A = np.random.random((5, 5, 3))
Q16_B = np.random.random((5, 5))
Q16 = Q16_A * Q16_B[:, :, np.newaxis]     # B: (5,5) → (5,5,1) → broadcasts to (5,5,3)
print("\nQuestion 16: (5,5,3) × (5,5) via broadcasting")
print(f"  A shape: {Q16_A.shape},  B shape: {Q16_B.shape},  Result shape: {Q16.shape}")

# ─────────────────────────────────────────────────────────────────────────────
# Question 17: Extract all contiguous 3×3 blocks from a random 10×10 matrix
# ─────────────────────────────────────────────────────────────────────────────
# sliding_window_view slides a (3,3) window over every valid position.
# A 10×10 matrix has (10-3+1)=8 valid starting rows and 8 valid starting cols,
# so the result shape is (8, 8, 3, 3): 64 overlapping 3×3 blocks.
Q17 = np.random.random((10, 10))
Q17_blocks = np.lib.stride_tricks.sliding_window_view(Q17, (3, 3))
print("\nQuestion 17: All contiguous 3×3 blocks from a 10×10 matrix")
print(f"  Matrix shape: {Q17.shape}")
print(f"  Blocks shape: {Q17_blocks.shape}  (row_starts × col_starts × 3 × 3)")
print("  First block (top-left corner):")
print(np.round(Q17_blocks[0, 0], 4))

# ─────────────────────────────────────────────────────────────────────────────
# Question 18: Block-sum of a 16×16 array with 4×4 blocks
# ─────────────────────────────────────────────────────────────────────────────
# Reshape to (4, 4, 4, 4) — axes 0 and 2 index the 4 row-blocks / col-blocks;
# axes 1 and 3 index the 4 elements inside each block row / col.
# Summing over axes (1, 3) collapses the within-block dimensions, leaving a
# (4, 4) array where each entry is the sum of one 4×4 block.
Q18 = np.random.random((16, 16))
Q18_block_sum = Q18.reshape(4, 4, 4, 4).sum(axis=(1, 3))
print("\nQuestion 18: 4×4 block-sums of a 16×16 array")
print(f"  Input shape:      {Q18.shape}")
print(f"  Block-sum shape:  {Q18_block_sum.shape}  (4 row-blocks × 4 col-blocks)")
print(np.round(Q18_block_sum, 4))


Question 1: Null array of size 10, fifth value = 1
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]

Question 2: Reversed array
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]

Question 3: 3×3 matrix with values 0–8
[[0 1 2]
 [3 4 5]
 [6 7 8]]

Question 4: Indices of non-zero elements in [1 2 0 0 4 0]
[0 1 4]

Question 5: 3×3×3 random array
[[[0.37454012 0.95071431 0.73199394]
  [0.59865848 0.15601864 0.15599452]
  [0.05808361 0.86617615 0.60111501]]

 [[0.70807258 0.02058449 0.96990985]
  [0.83244264 0.21233911 0.18182497]
  [0.18340451 0.30424224 0.52475643]]

 [[0.43194502 0.29122914 0.61185289]
  [0.13949386 0.29214465 0.36636184]
  [0.45606998 0.78517596 0.19967378]]]

Question 6: Min and Max of a 10×10 random array
  Max: 0.986887
  Min: 0.005522

Question 7: Mean of a size-30 random vector
[0.86073058 0.00695213 0.5107473  0.417411   0.22210781 0.11986537
 0.33761517 0.9429097  0.32320293 0.51879062 0.70301896 0.3636296
 0.97178208 0.96244729 0.2517823  0.49724851 0.30087831 0.28484049
 0.03688695 0.60956433 0.

# Part C Code Update for Reproducibility


In [24]:
# Original Code
import numpy as np
data = np.random.randn(100, 3) # simulate returns
sample = data[np.random.choice(100, 20)] # take 20 rows
print("mean of sample:", sample.mean())

mean of sample: -0.0770276347535739


In [25]:
# Code Adjusted for Reproducibility
import numpy as np
np.random.seed(42) # Added line to set the random seed making the number no longer random
data = np.random.randn(100, 3) # simulate returns
sample = data[np.random.choice(100, 20)] # take 20 rows
print("mean of sample:", sample.mean())

mean of sample: 0.0023934932964601086
